name: air
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  # app_settings: ^4.2.0
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.8
  # flutter_cube: ^0.1.1
  model_viewer_plus: ^1.9.1
  flutter_spinkit: 5.1.0
  font_awesome_flutter: 10.2.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  # email_validator: ^2.0.1
  intl: ^0.20.2
  http: ^1.1.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.1
  path_provider: ^2.0.15
  flutter_tts: ^3.8.5
  record: ^5.2.1 
  # flutter_audio_waveforms: ^1.2.0
  camera: ^0.10.5+5
  image: ^4.0.17
  table_calendar: ^3.0.9
  fl_chart: ^0.65.0
  timeline_tile: ^2.0.0
  flutter_local_notifications: ^19.0.0
  workmanager: 0.9.0
  timezone: ^0.10.1
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  device_info_plus: ^9.1.2
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  record_linux: ^1.2.1

flutter:

  uses-material-design: true
  assets:
    - assets/air_robot_head1.PNG
    - assets/air_robot_head2.PNG
    - .env
    - assets/scripts/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
